_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.0
            "8":
                - 2
                - 5
            "12": 0.19.0
            "13": darwin-arm64
epochs:
    value: 1
hidden_dim:
    value: 448
learning_rate:
    value: 0.0006
weight_decay:
    value: 0.0002
